Implement freq_obs for sampling observations prior to optimization
pastas/pastas pull request #649
Opened 2023-10-02 12:14 UTC by dbrakenhoff

# Short Description
This allows users to select a different time step for the observation data in `ml.solve()`. The model time step remains unchanged but the optimization is performed on a sample of the original oseries. E.g., model timestep is daily, but the model is fit on head observations once every 14 days:

```python
ml.solve(freq_obs="14D")
```

# Checklist before PR can be merged:
- [x] is documented
- [x] Format code with [Black formatting](https://black.readthedocs.io)
- [x] type hints for functions and methods
- [x] tests added / passed
- [x] Example (for new features)
- [x] Remove output for all notebooks with changes

2023-10-03 10:06 UTC, dbrakenhoff commented
Test fails unrelated to this PR

2023-11-23 08:16 UTC, raoulcollenteur requested changes

2023-11-23 08:16 UTC, raoulcollenteur commented on pastas/model.py
> +        freq_obs: Optional[str] = None,
Do we need this here? Could this not be handled by the freq argument?

2023-11-23 08:16 UTC, raoulcollenteur commented on pastas/model.py
> +        freq_obs: Optional[str] = None,
Docstring is missing

2023-11-23 08:16 UTC, raoulcollenteur commented on pastas/model.py
> +        freq_obs: Optional[str] = None,
Docstring is missing

2023-11-23 08:19 UTC, raoulcollenteur commented
Thanks for the PR, this is a nice feature I think. Two things:

- Do we need the 'freq_obs' argument for the ml.observations? Can we need handle this through the 'freq' argument and only add freq_obs to ml.solve?
- Docstrings are missing for the new arguments.

ps. Update from dev-branch should solve CI issues :) 

Cheers,
Raoul

2023-11-28 16:43 UTC, raoulcollenteur approved these changes

2023-11-28 16:44 UTC, raoulcollenteur approved these changes

2023-11-28 16:44 UTC, raoulcollenteur commented
Thanks for the last changes! Merging :)

2023-11-28 16:45 UTC, merged