Add Futurewarning to Edelman response function for deprecation in pastas 2.0
pastas/pastas pull request #798
Opened 2024-08-05 12:20 UTC by martinvonk

# Short Description
Add deprecation warning for Edelman response function #475 
Edelman added to the pastas-plugins library in pull request [#9](https://github.com/pastas/pastas-plugins/pull/9)

2024-08-05 12:59 UTC, martinvonk commented
Fixed the failing ruff tests with #799

2024-08-05 14:35 UTC, raoulcollenteur requested changes
Let's stick to how all other warnings are throw for consistency. Can you change to logger.warning?

2024-08-05 14:35 UTC, raoulcollenteur commented on pastas/rfunc.py
> +            "This response function `Edelman` will be deprecated in Pastas "
The response function

2024-08-05 14:35 UTC, raoulcollenteur commented on pastas/rfunc.py
> +from warnings import warn
Please follow: https://pastas.readthedocs.io/latest/developers/code_style.html

2024-08-05 14:45 UTC, martinvonk commented
I can change to `logger.warning` but we now have three methods for deprecation in the code: 

[logger.warning](https://github.com/pastas/pastas/blob/b214d48dde75d2864af6d8bf51bb158103be4c52/pastas/version.py#L50-L59)
[PastasDeprecationWarning decorator](https://github.com/pastas/pastas/blob/b214d48dde75d2864af6d8bf51bb158103be4c52/pastas/decorators.py#L65-L73)
[FutureWarning](https://github.com/pastas/pastas/blob/b214d48dde75d2864af6d8bf51bb158103be4c52/pastas/stats/metrics.py#L690C1-L694C6)

Maybe we could change the PastasDeprecationWarning to call the `__name__` of the function/class and have an argument for the version when something will be deprecated.

2024-08-06 14:01 UTC, dbrakenhoff approved these changes

2024-08-06 14:03 UTC, merged